version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
    depends_on:
      - user

  movie:
    build: ./movie
    ports:
      - "${MOVIE_PORT}:${MOVIE_PORT}"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MOVIE_PORT=${MOVIE_PORT}
      - PYTHONPATH=/app:/app/common
    env_file:
      - .env
    depends_on:
      - mongo_db
    volumes:
      - ./common:/app/common

  user:
    build: ./user
    ports:
      - "${USER_PORT}:${USER_PORT}"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - USER_PORT=${USER_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - BOOKING_HOST=${BOOKING_HOST}
      - BOOKING_PORT=${BOOKING_PORT}
      - MOVIE_HOST=${MOVIE_HOST}
      - MOVIE_PORT=${MOVIE_PORT}
      - PYTHONPATH=/app:/app/common
    env_file:
      - .env
    depends_on:
      - mongo_db
      - booking
      - movie
    volumes:
      - ./common:/app/common

  booking:
    build: ./booking
    ports:
      - "${BOOKING_PORT}:${BOOKING_PORT}"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - BOOKING_PORT=${BOOKING_PORT}
      - SHOWTIME_HOST=${SHOWTIME_HOST}
      - SHOWTIME_PORT=${SHOWTIME_PORT}
      - PYTHONPATH=/app:/app/common
    env_file:
      - .env
    depends_on:
      - mongo_db
      - showtime
    volumes:
      - ./common:/app/common

  showtime:
    build: ./showtime
    ports:
      - "${SHOWTIME_PORT}:${SHOWTIME_PORT}"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - SHOWTIME_PORT=${SHOWTIME_PORT}
      - PYTHONPATH=/app:/app/common
    env_file:
      - .env
    depends_on:
      - mongo_db
    volumes:
      - ./common:/app/common

  mongo_db:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

volumes:
  mongo_data:
