version: "3.9"

services:
  # frontend:
  #   build: ./frontend/
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - user
  #     - movie

  movie:
    build: ./movie/
    ports:
      - "3200:3200"

  showtime:
    build: ./showtime/
    ports:
      - "3202:3202"
    environment:
      - PYTHONUNBUFFERED=1

  user:
    build: ./user/
    ports:
      - "3203:3203"
    depends_on:
      - booking
      - movie
    environment:
      - PYTHONUNBUFFERED=1

  booking:
    build: ./booking/
    ports:
      - "3201:3201"
    depends_on:
      - showtime
    environment:
      - PYTHONUNBUFFERED=1
